// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHvVzhiTPFR7bHHAWIImAxRzSEuC0rw8',
    appId: '1:983069725728:web:1e009353d88aecfb5ad845',
    messagingSenderId: '983069725728',
    projectId: 'hack30-93be7',
    authDomain: 'hack30-93be7.firebaseapp.com',
    databaseURL: 'https://hack30-93be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hack30-93be7.firebasestorage.app',
    measurementId: 'G-1J5W8CF2XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGJFjuVN-rHpMj2HGpTFAqziYKm5IfPM',
    appId: '1:983069725728:android:26ef42367b11aed75ad845',
    messagingSenderId: '983069725728',
    projectId: 'hack30-93be7',
    databaseURL: 'https://hack30-93be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hack30-93be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiet90Ftz6CXSOT9PW6z4xljmljy-Lg4',
    appId: '1:983069725728:ios:bbb1856bf6cc02ed5ad845',
    messagingSenderId: '983069725728',
    projectId: 'hack30-93be7',
    databaseURL: 'https://hack30-93be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hack30-93be7.firebasestorage.app',
    iosBundleId: 'com.example.hack302026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuiet90Ftz6CXSOT9PW6z4xljmljy-Lg4',
    appId: '1:983069725728:ios:bbb1856bf6cc02ed5ad845',
    messagingSenderId: '983069725728',
    projectId: 'hack30-93be7',
    databaseURL: 'https://hack30-93be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hack30-93be7.firebasestorage.app',
    iosBundleId: 'com.example.hack302026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZHvVzhiTPFR7bHHAWIImAxRzSEuC0rw8',
    appId: '1:983069725728:web:f4cd0677c553ae545ad845',
    messagingSenderId: '983069725728',
    projectId: 'hack30-93be7',
    authDomain: 'hack30-93be7.firebaseapp.com',
    databaseURL: 'https://hack30-93be7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hack30-93be7.firebasestorage.app',
    measurementId: 'G-XKN8GJPS5Z',
  );

}